# Generated by Django 2.2 on 2021-05-03 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_app', '0004_auto_20210503_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.BooleanField(choices=[('true', 'Male'), ('false', 'Female')], null=True),
        ),
    ]
