# Generated by Django 2.2 on 2021-05-03 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_app', '0005_auto_20210503_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
