# Generated by Django 2.2 on 2021-05-08 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workout_app', '0006_auto_20210503_1314'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('workout_date', models.DateTimeField()),
                ('exercise', models.CharField(max_length=100)),
                ('weight', models.IntegerField()),
                ('reps', models.IntegerField()),
                ('sets', models.IntegerField()),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout', to='workout_app.User')),
            ],
        ),
    ]
