# Generated by Django 2.2 on 2021-05-09 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_app', '0007_workout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='reps',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='sets',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='weight',
            field=models.IntegerField(null=True),
        ),
    ]
